create extension if not exists pgcrypto;

drop table if exists public.saved_searches cascade;
drop table if exists public.favorites cascade;
drop table if exists public.listing_locations cascade;
drop table if exists public.listing_materials cascade;
drop table if exists public.listing_images cascade;
drop table if exists public.listings cascade;
drop table if exists public.subregions cascade;
drop table if exists public.regions cascade;
drop table if exists public.colors cascade;
drop table if exists public.materials cascade;
drop table if exists public.manufacturers cascade;
drop table if exists public.field_help cascade;
drop table if exists public.user_roles cascade;
drop table if exists public.roles cascade;
drop table if exists public.profiles cascade;

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text,contact_email text,whatsapp_number text,preferred_contact_method text check(preferred_contact_method in('email','whatsapp','both')),default_shipping boolean default true,default_region_ids uuid[] default '{}',default_subregion_ids uuid[] default '{}',last_active_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.roles(id uuid primary key default gen_random_uuid(),key text not null unique,label text not null,created_at timestamptz not null default now());
insert into public.roles(key,label) values('member','משתמשת'),('admin','מנהלת'),('instructor','מדריכה');
create table public.user_roles(user_id uuid references auth.users(id) on delete cascade,role_id uuid references public.roles(id) on delete cascade,granted_by uuid references auth.users(id),created_at timestamptz not null default now(),primary key(user_id,role_id));
create table public.manufacturers(id uuid primary key default gen_random_uuid(),name text not null,normalized_name text generated always as(lower(trim(name))) stored,created_by uuid references auth.users(id),status text not null default'active' check(status in('active','merged','hidden')),merged_into_id uuid references public.manufacturers(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index manufacturers_normalized_active_idx on public.manufacturers(normalized_name) where status='active';
create table public.materials(id uuid primary key default gen_random_uuid(),name text not null,normalized_name text generated always as(lower(trim(name))) stored,parent_material_id uuid references public.materials(id),vegan boolean not null default true,material_origin text not null default'natural' check(material_origin in('natural','artificial','synthetic')),created_by uuid references auth.users(id),status text not null default'active' check(status in('active','merged','hidden')),merged_into_id uuid references public.materials(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index materials_normalized_active_idx on public.materials(normalized_name) where status='active';
create table public.colors(key text primary key,label text not null,hex text not null,sort_order smallint not null,active boolean not null default true);
create table public.regions(id uuid primary key default gen_random_uuid(),name text not null unique,sort_order smallint not null,active boolean not null default true);
create table public.subregions(id uuid primary key default gen_random_uuid(),region_id uuid not null references public.regions(id) on delete cascade,name text not null,sort_order smallint not null,active boolean not null default true,unique(region_id,name));
create table public.listings(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id),manufacturer_id uuid not null references public.manufacturers(id),design text not null default'',model text,price integer not null default 0 check(price>=0),description text,size text not null default'',size_note text,gsm text not null default'unknown' check(gsm in('lte_180','190','200','210','220','230','240','250','260','270','280','290','300','310','320','330','340','gte_350','unknown')),condition text not null default'' check(condition in('','unused','lightly_used','broken_in','lightly_worn','worn')),defects text[] not null default array['none']::text[],defects_description text,shipping_available boolean not null default true,more_info_url text,colors text[] not null default'{}',color_patterns text[] not null default'{}',status text not null default'draft' check(status in('draft','active','paused','deleted')),impressions_count bigint not null default 0,views_count bigint not null default 0,favorites_count bigint not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),paused_at timestamptz,deleted_at timestamptz);
create table public.listing_images(id uuid primary key default gen_random_uuid(),listing_id uuid not null references public.listings(id) on delete cascade,owner_id uuid not null references auth.users(id),storage_path text not null unique,image_type text not null check(image_type in('listing','defect')),position smallint not null default 0,created_at timestamptz not null default now());
create table public.listing_materials(listing_id uuid not null references public.listings(id) on delete cascade,material_id uuid not null references public.materials(id),percentage numeric(5,2) not null check(percentage>0 and percentage<=100),position smallint not null default 0,primary key(listing_id,material_id));
create table public.listing_locations(id uuid primary key default gen_random_uuid(),listing_id uuid not null references public.listings(id) on delete cascade,region_id uuid not null references public.regions(id),subregion_id uuid references public.subregions(id));
create table public.favorites(user_id uuid not null references auth.users(id) on delete cascade,listing_id uuid not null references public.listings(id) on delete cascade,created_at timestamptz not null default now(),primary key(user_id,listing_id));
create table public.saved_searches(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,filters jsonb not null default'{}',sort_key text not null default'stable_random',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.field_help(id uuid primary key default gen_random_uuid(),field_key text not null unique,content text not null,is_active boolean not null default true,show_in_form boolean not null default false,show_on_listing boolean not null default false,show_in_filter boolean not null default false,updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));

create index listings_status_idx on public.listings(status);create index listings_owner_idx on public.listings(owner_id);create index listings_manufacturer_idx on public.listings(manufacturer_id);create index listings_size_idx on public.listings(size);create index listings_gsm_idx on public.listings(gsm);create index listings_price_idx on public.listings(price);create index listing_material_idx on public.listing_materials(material_id);create index listing_region_idx on public.listing_locations(region_id);create index listing_subregion_idx on public.listing_locations(subregion_id);create index saved_searches_user_idx on public.saved_searches(user_id);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,display_name,contact_email) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.email) on conflict(id) do nothing;insert into public.user_roles(user_id,role_id) select new.id,id from public.roles where key='member' on conflict do nothing;return new;end$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.sync_favorites_count() returns trigger language plpgsql security definer set search_path=public as $$begin if tg_op='INSERT' then update public.listings set favorites_count=favorites_count+1 where id=new.listing_id;return new;else update public.listings set favorites_count=greatest(0,favorites_count-1) where id=old.listing_id;return old;end if;end$$;
create trigger favorite_count_insert after insert on public.favorites for each row execute procedure public.sync_favorites_count();create trigger favorite_count_delete after delete on public.favorites for each row execute procedure public.sync_favorites_count();
create or replace function public.increment_listing_view(p_listing_id uuid) returns void language sql security definer set search_path=public as $$update public.listings set views_count=views_count+1 where id=p_listing_id and status='active'$$;
create or replace function public.increment_listing_impression(p_listing_id uuid) returns void language sql security definer set search_path=public as $$update public.listings set impressions_count=impressions_count+1 where id=p_listing_id and status='active'$$;
create or replace function public.get_listing_contact(p_listing_id uuid) returns table(display_name text,contact_email text,whatsapp_number text,preferred_contact_method text) language sql security definer set search_path=public as $$select p.display_name,p.contact_email,p.whatsapp_number,p.preferred_contact_method from public.listings l join public.profiles p on p.id=l.owner_id where l.id=p_listing_id and l.status='active' and auth.uid() is not null$$;
grant execute on function public.increment_listing_view(uuid) to anon,authenticated;grant execute on function public.increment_listing_impression(uuid) to anon,authenticated;grant execute on function public.get_listing_contact(uuid) to authenticated;

alter table public.profiles enable row level security;alter table public.roles enable row level security;alter table public.user_roles enable row level security;alter table public.manufacturers enable row level security;alter table public.materials enable row level security;alter table public.colors enable row level security;alter table public.regions enable row level security;alter table public.subregions enable row level security;alter table public.listings enable row level security;alter table public.listing_images enable row level security;alter table public.listing_materials enable row level security;alter table public.listing_locations enable row level security;alter table public.favorites enable row level security;alter table public.saved_searches enable row level security;alter table public.field_help enable row level security;
create policy p_profiles_select on public.profiles for select to authenticated using(id=auth.uid());create policy p_profiles_update on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy p_roles_read on public.roles for select to authenticated using(true);create policy p_userroles_read on public.user_roles for select to authenticated using(user_id=auth.uid());
create policy p_man_read on public.manufacturers for select to anon,authenticated using(status='active');create policy p_man_insert on public.manufacturers for insert to authenticated with check(created_by=auth.uid());
create policy p_mat_read on public.materials for select to anon,authenticated using(status='active');create policy p_mat_insert on public.materials for insert to authenticated with check(created_by=auth.uid());
create policy p_colors_read on public.colors for select to anon,authenticated using(active);create policy p_regions_read on public.regions for select to anon,authenticated using(active);create policy p_subregions_read on public.subregions for select to anon,authenticated using(active);create policy p_help_read on public.field_help for select to anon,authenticated using(is_active);
create policy p_listings_public on public.listings for select to anon,authenticated using(status='active');create policy p_listings_owner_select on public.listings for select to authenticated using(owner_id=auth.uid());create policy p_listings_insert on public.listings for insert to authenticated with check(owner_id=auth.uid());create policy p_listings_update on public.listings for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy p_images_public on public.listing_images for select to anon,authenticated using(exists(select 1 from public.listings l where l.id=listing_id and l.status='active'));create policy p_images_owner_select on public.listing_images for select to authenticated using(owner_id=auth.uid());create policy p_images_insert on public.listing_images for insert to authenticated with check(owner_id=auth.uid());create policy p_images_delete on public.listing_images for delete to authenticated using(owner_id=auth.uid());
create policy p_lm_read on public.listing_materials for select to anon,authenticated using(exists(select 1 from public.listings l where l.id=listing_id and(l.status='active' or l.owner_id=auth.uid())));create policy p_lm_write on public.listing_materials for all to authenticated using(exists(select 1 from public.listings l where l.id=listing_id and l.owner_id=auth.uid())) with check(exists(select 1 from public.listings l where l.id=listing_id and l.owner_id=auth.uid()));
create policy p_ll_read on public.listing_locations for select to anon,authenticated using(exists(select 1 from public.listings l where l.id=listing_id and(l.status='active' or l.owner_id=auth.uid())));create policy p_ll_write on public.listing_locations for all to authenticated using(exists(select 1 from public.listings l where l.id=listing_id and l.owner_id=auth.uid())) with check(exists(select 1 from public.listings l where l.id=listing_id and l.owner_id=auth.uid()));
create policy p_fav on public.favorites for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());create policy p_search on public.saved_searches for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('listing-images','listing-images',false,6291456,array['image/jpeg','image/png','image/webp']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy p_storage_insert on storage.objects for insert to authenticated with check(bucket_id='listing-images' and(storage.foldername(name))[1]=auth.uid()::text);create policy p_storage_read on storage.objects for select to anon,authenticated using(bucket_id='listing-images' and exists(select 1 from public.listing_images li join public.listings l on l.id=li.listing_id where li.storage_path=name and(l.status='active' or l.owner_id=auth.uid())));create policy p_storage_delete on storage.objects for delete to authenticated using(bucket_id='listing-images' and(storage.foldername(name))[1]=auth.uid()::text);
